#!/bin/ksh
today_date=`cut -c9-16 $data/file/MFLAGS`
export DD_GLBM=$data/glif/${today_date}GLBM
run.sh -t CNVSUMGLCC
((yesterday_date=today_date-1))
if [ ! -e $data/glif/${yesterday_date}GLBM ];then
   echo "there is no yesterday's sum glcc file please run again tomorrow"
   exit 0
fi
export DD_YESTERDAY=$data/glif/${yesterday_date}GLBM
export DD_TODAY=$data/glif/${today_date}GLBM
export DD_WRONGGLCC=$data/glif/WRONGGLCC
export DD_MFLAGS=$data/file/MFLAGS
cmd="run.sh -t"
while getopts bdft c ; do
   case $c in
      b) cmd="run.sh -b" ;;
      d) cmd="run.sh -d";;
      f) cmd="run.sh -f";;
      t) cmd="run.sh -t";;
   esac
done
shift `expr $OPTIND - 1`
$cmd CNVVALGLCC
cat $data/glif/WRONGGLCC

